export const SLOTS = {
    "1": "1AM - 3AM",
    "2": "2AM - 4AM",
    "3": "3AM - 5AM",
    "4": "4AM - 6AM",
    "5": "5AM - 7AM",
    "6": "6AM - 8AM",
    "7": "7AM - 9AM",
    "8": "8AM - 10AM",
    "9": "9AM - 11AM",
    "10": "10AM - 12AM",
    "11": "11AM - 1PM",
    "12": "12PM - 2PM",
    "13": "1PM - 3PM",
    "14": "2PM - 4PM",
    "15": "3PM - 5PM",
    "16": "4PM - 6PM",
    "17": "5PM - 7PM",
    "18": "6PM - 8PM",
    "19": "7PM - 9PM",
    "20": "8PM - 10PM",
    "21": "9PM - 11PM",
    "22": "10PM - 12PM",
    "23": "11PM - 1AM",
    "0": "12AM - 2AM"
};


export const CHARGE_KEYS = [
    'discountCharges',
    'emergencyCharges',
    'fridayCharges',
    'totalCharges',
    'callOutCharges',
    'advanceCharges', 
    'cancellationCharges',   
    'estimateCharges',
    'finalCharges',
    'labourCharges',
    'materialCharges',
    'otherCharges',
    'unitCharges',
    'vatCharges',
    'vatFinalCharges',
    'dueCharges',
    'additionalCharges'
];