module.exports = {
    //font-starts
    fel: { fontFamily: 'PoppinsEL' },
    fl: { fontFamily: 'PoppinsL' },
    fr: { fontFamily: 'PoppinsR' },
    fm: { fontFamily: 'PoppinsM' },
    fsb: { fontFamily: 'PoppinsSB' },
    fbo: { fontFamily: 'PoppinsBO' },
    feb: { fontFamily: 'PoppinsEB' },
    fbl: { fontFamily: 'PoppinsBL' },
    ft: { fontFamily: 'PoppinsT' },
    //font-ends
    //colors-starts
    brandC: { color: '#2eb0e4' },
    liteBlueC: { color: '#eff7fc' },
    yellowC: { color: '#f6b700' },
    liteYellowC: { color: '#fffcf1' },
    blackC: { color: '#525252' },
    liteBlackC: { color: '#7e7e7e' },
    greyC: { color: '#bababa' },
    liteGreyC: { color: '#F4F4F4' },
    ltGrayC: { color: '#d1d1d150' },
    ltblackC: { color: '#d1d1d1' },
    lGreyC: { color: '#60604E' },
    grayC: { color: '#ccc' },
    whiteC: { color: '#fff' },
    orangeC: { color: '#f6ad00' },
    cMaroon: { color: '#d36565' },
    //colors-ends
    //bg-starts
    brandBG: { backgroundColor: '#2eb0e4' },
    liteBlueBG: { backgroundColor: '#eff7fc' },
    yellowBG: { backgroundColor: '#f6b700' },
    liteYellowBG: { backgroundColor: '#fffcf1' },
    blackBG: { backgroundColor: '#525252' },
    liteBlackBG: { backgroundColor: '#7e7e7e' },
    liteGreyBG: { backgroundColor: '#F4F4F4' },
    ltGrayBG: { backgroundColor: '#d1d1d150' },
    lGreyBG: { backgroundColor: '#60604E' },
    whiteBG: { backgroundColor: '#fff' },
    //bg-ends
    section: {
        fontFamily: 'PoppinsR',
        fontSize: 14,
    },
    container: {
        padding: 20,
    },
    flexDR: {
        flexDirection: "row",
        //flex: 1,
    },
    flexDC: {
        flexDirection: "column",
    },
    flexDRR: {
        flexDirection: "row-reverse",
    },
    flexDCR: {
        flexDirection: "column-reverse",
    },
    directionLTR: { direction: 'ltr' },
    directionRTL: { direction: 'rtl' },
    justifyContentFS: { justifyContent: 'flex-start' },
    justifyContentFE: { justifyContent: 'flex-end' },
    justifyContentC: { justifyContent: 'center' },
    justifyContentSB: { justifyContent: 'space-between' },
    justifyContentSA: { justifyContent: 'space-around' },
    justifyContentSE: { justifyContent: 'space-evenly' },
    alignItemsS: { alignItems: 'stretch' },
    alignItemsFS: { alignItems: 'flex-start' },
    alignItemsFE: { alignItems: 'flex-end' },
    alignItemsC: { alignItems: 'center' },
    alignItemsB: { alignItems: 'baseline' },
    alignSelfS: { alignSelf: 'stretch' },
    alignSelfFS: { alignSelf: 'flex-start' },
    alignSelfFE: { alignSelf: 'flex-end' },
    alignSelfC: { alignSelf: 'center' },
    alignSelfB: { alignSelf: 'baseline' },
    alignContentS: { alignContent: 'stretch' },
    alignContentFS: { alignContent: 'flex-start' },
    alignContentFE: { alignContent: 'flex-end' },
    alignContentC: { alignContent: 'center' },
    alignContentSB: { alignContent: 'space-between' },
    alignContentSA: { alignContent: 'space-around' },
    flexWrapW: { flexWrap: 'wrap' },
    flexWrapN: { flexWrap: 'no-wrap' },
    flexDRSB: { flexDirection: "row", justifyContent: "space-between" },
    flexDRSA: { flexDirection: "row", justifyContent: 'space-around' },
    flexDRSE: { flexDirection: "row", justifyContent: 'space-evenly' },
    flexDCSB: { flexDirection: "column", justifyContent: "space-between" },
    flexDCSA: { flexDirection: "column", justifyContent: 'space-around' },
    flexDCSE: { flexDirection: "column", justifyContent: 'space-evenly' },
    flexDR_ALC: { flexDirection: "row", alignItems: 'center' },
    flexDR_JCC: { flexDirection: "row", justifyContent: 'center' },
    alignCenter: { alignItems: 'center', justifyContent: 'center' },
    textCenter: {
        textAlign: "center",
    },
    textLeft: {
        textAlign: "left",
    },
    textRight: {
        textAlign: "right",
    },
    borderRadius10: {
        borderRadius: 10,
    },
    borderRadius20: {
        borderRadius: 20,
    },
    borderRadius30: {
        borderRadius: 30,
    },
    //borderR100: { borderRadius: '100%' },
    imgFull: { width: "100%", },
    img95: { width: "95%" },
    img90: { width: "90%" },
    img80: { width: "80%" },
    img75: { width: "75%" },
    width100: { width: "100%" },
    width95: { width: "95%" },
    width90: { width: "90%" },
    width80: { width: "80%" },
    width75: { width: "75%" },
    width70: { width: "70%" },
    width60: { width: "60%" },
    width50: { width: "50%" },
    width40: { width: "40%" },
    width30: { width: "30%" },
    width20: { width: "20%" },
    width10: { width: "10%" },
    img100: { width: 100, height: 100 },
    imgg90: { width: 90, height: 90 },
    imgg80: { width: 80, height: 80 },
    imgg70: { width: 70, height: 70 },
    imgg60: { width: 60, height: 60 },
    img50: { width: 50, height: 50 },
    img40: { width: 40, height: 40 },
    img30: { width: 30, height: 30 },
    img20: { width: 20, height: 20 },
    img150: { width: 150, height: 150 },
    imgBR50: { width: 50, height: 50, borderRadius: 50 / 2 },
    imgBR100: { width: 100, height: 100, borderRadius: 100 / 2 },
    imgBR150: { width: 150, height: 150, borderRadius: 150 / 2 },
    spaceB5: { marginBottom: 5 },
    spaceB10: { marginBottom: 10 },
    spaceB20: { marginBottom: 20 },
    spaceB30: { marginBottom: 30 },
    spaceT5: { marginTop: 5 },
    spaceT10: { marginTop: 10 },
    spaceT20: { marginTop: 20 },
    spaceT30: { marginTop: 30 },
    line: { borderBottomColor: '#ccc', borderBottomWidth: 1 },
    lineP5: { borderBottomColor: '#ccc', borderBottomWidth: 1, paddingBottom: 5, },
    lineP10: { borderBottomColor: '#ccc', borderBottomWidth: 1, paddingBottom: 10, },
    lineP20: { borderBottomColor: '#ccc', borderBottomWidth: 1, paddingBottom: 20, },
    line5: { borderBottomColor: '#ccc', borderBottomWidth: 1, paddingBottom: 5, marginBottom: 5 },
    line10: { borderBottomColor: '#ccc', borderBottomWidth: 1, paddingBottom: 10, marginBottom: 10 },
    line20: { borderBottomColor: '#ccc', borderBottomWidth: 1, paddingBottom: 20, marginBottom: 20 },
    padding5: { padding: 5 },
    padding10: { padding: 10 },
    padding20: { padding: 20 },
    padding30: { padding: 30 },
    paddingL10: { paddingLeft: 10 },
    paddingL20: { paddingLeft: 20 },
    paddingL30: { paddingLeft: 30 },
    paddingR10: { paddingRight: 10 },
    paddingR20: { paddingRight: 20 },
    paddingR30: { paddingRight: 30 },
    paddingT10: { paddingTop: 10 },
    paddingT20: { paddingTop: 20 },
    paddingT30: { paddingTop: 30 },
    paddingB10: { paddingBottom: 10 },
    paddingB20: { paddingBottom: 20 },
    paddingB30: { paddingBottom: 30 },
    marginL5: { marginLeft: 5 },
    marginL10: { marginLeft: 10 },
    marginL20: { marginLeft: 20 },
    marginL30: { marginLeft: 30 },
    marginR5: { marginRight: 5 },
    marginR10: { marginRight: 10 },
    marginR20: { marginRight: 20 },
    marginR30: { marginRight: 30 },
    marginT5: { marginTop: 5 },
    marginT10: { marginTop: 10 },
    marginT20: { marginTop: 20 },
    marginT30: { marginTop: 30 },
    marginB5: { marginBottom: 5 },
    marginB10: { marginBottom: 10 },
    marginB20: { marginBottom: 20 },
    marginB30: { marginBottom: 30 },
    //font-size
    f10: { fontSize: 10 },
    f11: { fontSize: 11 },
    f12: { fontSize: 12 },
    f14: { fontSize: 14 },
    f16: { fontSize: 16 },
    f18: { fontSize: 18 },
    f20: { fontSize: 20 },
    f24: { fontSize: 24 },
    f30: { fontSize: 30 },
    //textTransform
    ttU: { textTransform: 'upperCase' },
    ttC: { textTransform: 'capitalize' },
    ttL: { textTransform: 'lowerCase' },
    //rotate
    //transform: rotate(20deg)
    transform45: { transform: [{ rotate: "45deg" }] },
    transform90: { transform: [{ rotate: "90deg" }] },
    transform45: { transform: [{ rotate: "45deg" }] },
    transform180: { transform: [{ rotate: "180deg" }] },
    //modal-css-start
    centeredView: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
    },
    modalView: {
        backgroundColor: "white",
        borderRadius: 10,
        padding: 10,
        height: 150,
        alignItems: "center",
        justifyContent: 'center',
        shadowColor: "#000",
        shadowOffset: {
            width: 2,
            height: 4
        },
        shadowOpacity: 0.5,
        shadowRadius: 5,
        elevation: 10,
        width: '90%'
    },
    modalText: {
        marginBottom: 15,
        textAlign: "center",
        color: '#60604E',
        fontSize: 18
    },
    Text: {
        fontFamily: 'PoppinsR'
    },
    //modal-css-ends
    //modal-new-starts
    modalNewView: {
        backgroundColor: "white",
        borderRadius: 10,
        width: '100%'
    },
    modalNewHeader: { padding: 20, backgroundColor: '#F2F4F8', borderTopLeftRadius: 10, borderTopRightRadius: 10, fontFamily: 'PoppinsR' },
    modalNewTitle: { marginTop: 20, marginBottom: 10, color: '#525252', fontSize: 18, fontFamily: 'PoppinsSB', textAlign: 'center', fontFamily: 'PoppinsR' },
    modalNewText: { color: '#525252', textAlign: 'center', fontFamily: 'PoppinsR' },
    modalNewBody: { padding: 20, fontFamily: 'PoppinsR' },
    //modal-new-ends
    //extra-css
    header: {
        width: "100%",
        height: 70,
        paddingLeft: 20,
        backgroundColor: "#2eb0e4",
        justifyContent: "center",
        borderBottomLeftRadius: 30,
        borderBottomRightRadius: 30,
        elevation: 10,
        shadowColor: "#000",
        color: "#fff",
    },
    headerTitle: {
        fontSize: 18,
        fontFamily: 'PoppinsSB',
        color: '#fff',
        textTransform: "uppercase",
    },
    backButton: {
        marginRight: 10,
        justifyContent: "center",
    },
    yellowBtn: {
        backgroundColor: '#f6b700',
        width: '70%',
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 10
    },
    blueBtn: {
        backgroundColor: '#2eb0e4',
        width: 100,
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 10
    },
    fixedContainer: { flex: 1 },
    fixedHeader: { position: 'absolute', top: 0, marginBottom: 200 },
    boxShadow: { shadowColor: "#00000050", shadowOffset: { width: 0, height: 2, }, shadowOpacity: 0.7, shadowRadius: 2.84, elevation: 5, },
    zIndex1: { zIndex: 1 },
    zIndex2: { zIndex: 2 },
    zIndex3: { zIndex: 3 },
    zIndex4: { zIndex: 4 },
    zIndex5: { zIndex: 5 },
}
